// Generated by `wit-bindgen` 0.21.0. DO NOT EDIT!
#include "bindings.h"


__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[static]usb-device.enumerate")))
extern void __wasm_import_wadu436_usb_device_static_usb_device_enumerate(uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[static]usb-device.request-device")))
extern void __wasm_import_wadu436_usb_device_static_usb_device_request_device(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, uintptr_t, size_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.descriptor")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_descriptor(int32_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.speed")))
extern int32_t __wasm_import_wadu436_usb_device_method_usb_device_speed(int32_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.configurations")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_configurations(int32_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.active-configuration")))
extern int32_t __wasm_import_wadu436_usb_device_method_usb_device_active_configuration(int32_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.open")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_open(int32_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.opened")))
extern int32_t __wasm_import_wadu436_usb_device_method_usb_device_opened(int32_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.reset")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_reset(int32_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.close")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_close(int32_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.select-configuration")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_select_configuration(int32_t, int32_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.claim-interface")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_claim_interface(int32_t, int32_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.release-interface")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_release_interface(int32_t, int32_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.clear-halt")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_clear_halt(int32_t, int32_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.read-control")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_read_control(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.write-control")))
extern int64_t __wasm_import_wadu436_usb_device_method_usb_device_write_control(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, uintptr_t, size_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.read-interrupt")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_read_interrupt(int32_t, int32_t, int64_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.write-interrupt")))
extern int64_t __wasm_import_wadu436_usb_device_method_usb_device_write_interrupt(int32_t, int32_t, uintptr_t, size_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.read-bulk")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_read_bulk(int32_t, int32_t, int64_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.write-bulk")))
extern int64_t __wasm_import_wadu436_usb_device_method_usb_device_write_bulk(int32_t, int32_t, uintptr_t, size_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.read-isochronous")))
extern void __wasm_import_wadu436_usb_device_method_usb_device_read_isochronous(int32_t, int32_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-device.write-isochronous")))
extern int64_t __wasm_import_wadu436_usb_device_method_usb_device_write_isochronous(int32_t, int32_t, uintptr_t, size_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-configuration.descriptor")))
extern void __wasm_import_wadu436_usb_device_method_usb_configuration_descriptor(int32_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-configuration.interfaces")))
extern void __wasm_import_wadu436_usb_device_method_usb_configuration_interfaces(int32_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-interface.descriptor")))
extern void __wasm_import_wadu436_usb_device_method_usb_interface_descriptor(int32_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-interface.endpoints")))
extern void __wasm_import_wadu436_usb_device_method_usb_interface_endpoints(int32_t, uintptr_t);

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[method]usb-endpoint.descriptor")))
extern void __wasm_import_wadu436_usb_device_method_usb_endpoint_descriptor(int32_t, uintptr_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void bindings_option_u16_free(bindings_option_u16_t *ptr) {
  if (ptr->is_some) {
  }
}

void bindings_option_u8_free(bindings_option_u8_t *ptr) {
  if (ptr->is_some) {
  }
}

void bindings_option_string_free(bindings_option_string_t *ptr) {
  if (ptr->is_some) {
    bindings_string_free(&ptr->val);
  }
}

void wadu436_usb_types_filter_free(wadu436_usb_types_filter_t *ptr) {
  bindings_option_u16_free(&ptr->vendor_id);
  bindings_option_u16_free(&ptr->product_id);
  bindings_option_u8_free(&ptr->class_code);
  bindings_option_u8_free(&ptr->subclass_code);
  bindings_option_u8_free(&ptr->protocol_code);
  bindings_option_string_free(&ptr->serial_number);
}

void wadu436_usb_descriptors_device_descriptor_free(wadu436_usb_descriptors_device_descriptor_t *ptr) {
  bindings_option_string_free(&ptr->product_name);
  bindings_option_string_free(&ptr->manufacturer_name);
  bindings_option_string_free(&ptr->serial_number);
}

void wadu436_usb_descriptors_configuration_descriptor_free(wadu436_usb_descriptors_configuration_descriptor_t *ptr) {
  bindings_option_string_free(&ptr->description);
}

void wadu436_usb_descriptors_interface_descriptor_free(wadu436_usb_descriptors_interface_descriptor_t *ptr) {
  bindings_option_string_free(&ptr->interface_name);
}

void wadu436_usb_device_device_descriptor_free(wadu436_usb_device_device_descriptor_t *ptr) {
  wadu436_usb_descriptors_device_descriptor_free(ptr);
}

void wadu436_usb_device_configuration_descriptor_free(wadu436_usb_device_configuration_descriptor_t *ptr) {
  wadu436_usb_descriptors_configuration_descriptor_free(ptr);
}

void wadu436_usb_device_interface_descriptor_free(wadu436_usb_device_interface_descriptor_t *ptr) {
  wadu436_usb_descriptors_interface_descriptor_free(ptr);
}

void wadu436_usb_device_filter_free(wadu436_usb_device_filter_t *ptr) {
  wadu436_usb_types_filter_free(ptr);
}

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[resource-drop]usb-device")))
extern void __wasm_import_wadu436_usb_device_usb_device_drop(int32_t handle);

void wadu436_usb_device_usb_device_drop_own(wadu436_usb_device_own_usb_device_t handle) {
  __wasm_import_wadu436_usb_device_usb_device_drop(handle.__handle);
}

wadu436_usb_device_borrow_usb_device_t wadu436_usb_device_borrow_usb_device(wadu436_usb_device_own_usb_device_t arg) {
  return (wadu436_usb_device_borrow_usb_device_t) { arg.__handle };
}

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[resource-drop]usb-configuration")))
extern void __wasm_import_wadu436_usb_device_usb_configuration_drop(int32_t handle);

void wadu436_usb_device_usb_configuration_drop_own(wadu436_usb_device_own_usb_configuration_t handle) {
  __wasm_import_wadu436_usb_device_usb_configuration_drop(handle.__handle);
}

wadu436_usb_device_borrow_usb_configuration_t wadu436_usb_device_borrow_usb_configuration(wadu436_usb_device_own_usb_configuration_t arg) {
  return (wadu436_usb_device_borrow_usb_configuration_t) { arg.__handle };
}

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[resource-drop]usb-interface")))
extern void __wasm_import_wadu436_usb_device_usb_interface_drop(int32_t handle);

void wadu436_usb_device_usb_interface_drop_own(wadu436_usb_device_own_usb_interface_t handle) {
  __wasm_import_wadu436_usb_device_usb_interface_drop(handle.__handle);
}

wadu436_usb_device_borrow_usb_interface_t wadu436_usb_device_borrow_usb_interface(wadu436_usb_device_own_usb_interface_t arg) {
  return (wadu436_usb_device_borrow_usb_interface_t) { arg.__handle };
}

__attribute__((__import_module__("wadu436:usb/device@0.0.1"), __import_name__("[resource-drop]usb-endpoint")))
extern void __wasm_import_wadu436_usb_device_usb_endpoint_drop(int32_t handle);

void wadu436_usb_device_usb_endpoint_drop_own(wadu436_usb_device_own_usb_endpoint_t handle) {
  __wasm_import_wadu436_usb_device_usb_endpoint_drop(handle.__handle);
}

wadu436_usb_device_borrow_usb_endpoint_t wadu436_usb_device_borrow_usb_endpoint(wadu436_usb_device_own_usb_endpoint_t arg) {
  return (wadu436_usb_device_borrow_usb_endpoint_t) { arg.__handle };
}

void wadu436_usb_device_list_own_usb_device_free(wadu436_usb_device_list_own_usb_device_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void wadu436_usb_device_option_own_usb_device_free(wadu436_usb_device_option_own_usb_device_t *ptr) {
  if (ptr->is_some) {
  }
}

void wadu436_usb_device_list_own_usb_configuration_free(wadu436_usb_device_list_own_usb_configuration_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void bindings_list_u8_free(bindings_list_u8_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void wadu436_usb_device_list_own_usb_interface_free(wadu436_usb_device_list_own_usb_interface_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void wadu436_usb_device_list_own_usb_endpoint_free(wadu436_usb_device_list_own_usb_endpoint_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void bindings_string_set(bindings_string_t *ret, char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void bindings_string_dup(bindings_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void bindings_string_free(bindings_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void wadu436_usb_device_static_usb_device_enumerate(wadu436_usb_device_list_own_usb_device_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_static_usb_device_enumerate(ptr);
  *ret = (wadu436_usb_device_list_own_usb_device_t) { (wadu436_usb_device_own_usb_device_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wadu436_usb_device_static_usb_device_request_device(wadu436_usb_device_filter_t *filter, wadu436_usb_device_option_own_usb_device_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t option;
  int32_t option1;
  if (((*filter).vendor_id).is_some) {
    const uint16_t *payload0 = &((*filter).vendor_id).val;
    option = 1;
    option1 = (int32_t) (*payload0);
  } else {
    option = 0;
    option1 = 0;
  }
  int32_t option4;
  int32_t option5;
  if (((*filter).product_id).is_some) {
    const uint16_t *payload3 = &((*filter).product_id).val;
    option4 = 1;
    option5 = (int32_t) (*payload3);
  } else {
    option4 = 0;
    option5 = 0;
  }
  int32_t option8;
  int32_t option9;
  if (((*filter).class_code).is_some) {
    const uint8_t *payload7 = &((*filter).class_code).val;
    option8 = 1;
    option9 = (int32_t) (*payload7);
  } else {
    option8 = 0;
    option9 = 0;
  }
  int32_t option12;
  int32_t option13;
  if (((*filter).subclass_code).is_some) {
    const uint8_t *payload11 = &((*filter).subclass_code).val;
    option12 = 1;
    option13 = (int32_t) (*payload11);
  } else {
    option12 = 0;
    option13 = 0;
  }
  int32_t option16;
  int32_t option17;
  if (((*filter).protocol_code).is_some) {
    const uint8_t *payload15 = &((*filter).protocol_code).val;
    option16 = 1;
    option17 = (int32_t) (*payload15);
  } else {
    option16 = 0;
    option17 = 0;
  }
  int32_t option20;
  uintptr_t option21;
  size_t option22;
  if (((*filter).serial_number).is_some) {
    const bindings_string_t *payload19 = &((*filter).serial_number).val;
    option20 = 1;
    option21 = (int32_t) (*payload19).ptr;
    option22 = (int32_t) (*payload19).len;
  } else {
    option20 = 0;
    option21 = 0;
    option22 = 0;
  }
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_static_usb_device_request_device(option, option1, option4, option5, option8, option9, option12, option13, option16, option17, option20, option21, option22, ptr);
  wadu436_usb_device_option_own_usb_device_t option23;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option23.is_some = false;
      break;
    }
    case 1: {
      option23.is_some = true;
      option23.val = (wadu436_usb_device_own_usb_device_t) { *((int32_t*) (ptr + 4)) };
      break;
    }
  }
  *ret = option23;
}

void wadu436_usb_device_method_usb_device_descriptor(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_device_descriptor_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[52];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_device_descriptor((self).__handle, ptr);
  bindings_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (bindings_string_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  bindings_option_string_t option0;
  switch ((int32_t) (*((uint8_t*) (ptr + 12)))) {
    case 0: {
      option0.is_some = false;
      break;
    }
    case 1: {
      option0.is_some = true;
      option0.val = (bindings_string_t) { (uint8_t*)(*((int32_t*) (ptr + 16))), (size_t)(*((int32_t*) (ptr + 20))) };
      break;
    }
  }
  bindings_option_string_t option1;
  switch ((int32_t) (*((uint8_t*) (ptr + 24)))) {
    case 0: {
      option1.is_some = false;
      break;
    }
    case 1: {
      option1.is_some = true;
      option1.val = (bindings_string_t) { (uint8_t*)(*((int32_t*) (ptr + 28))), (size_t)(*((int32_t*) (ptr + 32))) };
      break;
    }
  }
  *ret = (wadu436_usb_descriptors_device_descriptor_t) {
    option,
    option0,
    option1,
    (wadu436_usb_types_version_t) {
      (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 36)))),
      (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 37)))),
      (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 38)))),
    },
    (uint16_t) ((int32_t) (*((uint16_t*) (ptr + 40)))),
    (uint16_t) ((int32_t) (*((uint16_t*) (ptr + 42)))),
    (wadu436_usb_types_version_t) {
      (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 44)))),
      (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 45)))),
      (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 46)))),
    },
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 47)))),
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 48)))),
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 49)))),
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 50)))),
  };
}

wadu436_usb_device_speed_t wadu436_usb_device_method_usb_device_speed(wadu436_usb_device_borrow_usb_device_t self) {
  int32_t ret = __wasm_import_wadu436_usb_device_method_usb_device_speed((self).__handle);
  return ret;
}

void wadu436_usb_device_method_usb_device_configurations(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_list_own_usb_configuration_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_device_configurations((self).__handle, ptr);
  *ret = (wadu436_usb_device_list_own_usb_configuration_t) { (wadu436_usb_device_own_usb_configuration_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

wadu436_usb_device_own_usb_configuration_t wadu436_usb_device_method_usb_device_active_configuration(wadu436_usb_device_borrow_usb_device_t self) {
  int32_t ret = __wasm_import_wadu436_usb_device_method_usb_device_active_configuration((self).__handle);
  return (wadu436_usb_device_own_usb_configuration_t) { ret };
}

void wadu436_usb_device_method_usb_device_open(wadu436_usb_device_borrow_usb_device_t self) {
  __wasm_import_wadu436_usb_device_method_usb_device_open((self).__handle);
}

bool wadu436_usb_device_method_usb_device_opened(wadu436_usb_device_borrow_usb_device_t self) {
  int32_t ret = __wasm_import_wadu436_usb_device_method_usb_device_opened((self).__handle);
  return ret;
}

void wadu436_usb_device_method_usb_device_reset(wadu436_usb_device_borrow_usb_device_t self) {
  __wasm_import_wadu436_usb_device_method_usb_device_reset((self).__handle);
}

void wadu436_usb_device_method_usb_device_close(wadu436_usb_device_borrow_usb_device_t self) {
  __wasm_import_wadu436_usb_device_method_usb_device_close((self).__handle);
}

void wadu436_usb_device_method_usb_device_select_configuration(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_borrow_usb_configuration_t configuration) {
  __wasm_import_wadu436_usb_device_method_usb_device_select_configuration((self).__handle, (configuration).__handle);
}

void wadu436_usb_device_method_usb_device_claim_interface(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_borrow_usb_interface_t interface) {
  __wasm_import_wadu436_usb_device_method_usb_device_claim_interface((self).__handle, (interface).__handle);
}

void wadu436_usb_device_method_usb_device_release_interface(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_borrow_usb_interface_t interface) {
  __wasm_import_wadu436_usb_device_method_usb_device_release_interface((self).__handle, (interface).__handle);
}

void wadu436_usb_device_method_usb_device_clear_halt(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_borrow_usb_endpoint_t endpoint) {
  __wasm_import_wadu436_usb_device_method_usb_device_clear_halt((self).__handle, (endpoint).__handle);
}

void wadu436_usb_device_method_usb_device_read_control(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_control_setup_t *request, uint16_t length, bindings_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_device_read_control((self).__handle, (int32_t) (*request).request_type, (int32_t) (*request).request_recipient, (int32_t) ((*request).request), (int32_t) ((*request).value), (int32_t) ((*request).index), (int32_t) (length), ptr);
  *ret = (bindings_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

uint64_t wadu436_usb_device_method_usb_device_write_control(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_control_setup_t *request, bindings_list_u8_t *data) {
  int64_t ret = __wasm_import_wadu436_usb_device_method_usb_device_write_control((self).__handle, (int32_t) (*request).request_type, (int32_t) (*request).request_recipient, (int32_t) ((*request).request), (int32_t) ((*request).value), (int32_t) ((*request).index), (int32_t) (*data).ptr, (int32_t) (*data).len);
  return (uint64_t) (ret);
}

void wadu436_usb_device_method_usb_device_read_interrupt(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_borrow_usb_endpoint_t endpoint, uint64_t length, bindings_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_device_read_interrupt((self).__handle, (endpoint).__handle, (int64_t) (length), ptr);
  *ret = (bindings_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

uint64_t wadu436_usb_device_method_usb_device_write_interrupt(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_borrow_usb_endpoint_t endpoint, bindings_list_u8_t *data) {
  int64_t ret = __wasm_import_wadu436_usb_device_method_usb_device_write_interrupt((self).__handle, (endpoint).__handle, (int32_t) (*data).ptr, (int32_t) (*data).len);
  return (uint64_t) (ret);
}

void wadu436_usb_device_method_usb_device_read_bulk(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_borrow_usb_endpoint_t endpoint, uint64_t length, bindings_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_device_read_bulk((self).__handle, (endpoint).__handle, (int64_t) (length), ptr);
  *ret = (bindings_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

uint64_t wadu436_usb_device_method_usb_device_write_bulk(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_borrow_usb_endpoint_t endpoint, bindings_list_u8_t *data) {
  int64_t ret = __wasm_import_wadu436_usb_device_method_usb_device_write_bulk((self).__handle, (endpoint).__handle, (int32_t) (*data).ptr, (int32_t) (*data).len);
  return (uint64_t) (ret);
}

void wadu436_usb_device_method_usb_device_read_isochronous(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_borrow_usb_endpoint_t endpoint, bindings_list_u8_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_device_read_isochronous((self).__handle, (endpoint).__handle, ptr);
  *ret = (bindings_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

uint64_t wadu436_usb_device_method_usb_device_write_isochronous(wadu436_usb_device_borrow_usb_device_t self, wadu436_usb_device_borrow_usb_endpoint_t endpoint, bindings_list_u8_t *data) {
  int64_t ret = __wasm_import_wadu436_usb_device_method_usb_device_write_isochronous((self).__handle, (endpoint).__handle, (int32_t) (*data).ptr, (int32_t) (*data).len);
  return (uint64_t) (ret);
}

void wadu436_usb_device_method_usb_configuration_descriptor(wadu436_usb_device_borrow_usb_configuration_t self, wadu436_usb_device_configuration_descriptor_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[20];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_configuration_descriptor((self).__handle, ptr);
  bindings_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 4)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (bindings_string_t) { (uint8_t*)(*((int32_t*) (ptr + 8))), (size_t)(*((int32_t*) (ptr + 12))) };
      break;
    }
  }
  *ret = (wadu436_usb_descriptors_configuration_descriptor_t) {
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 0)))),
    option,
    (int32_t) (*((uint8_t*) (ptr + 16))),
    (int32_t) (*((uint8_t*) (ptr + 17))),
    (uint16_t) ((int32_t) (*((uint16_t*) (ptr + 18)))),
  };
}

void wadu436_usb_device_method_usb_configuration_interfaces(wadu436_usb_device_borrow_usb_configuration_t self, wadu436_usb_device_list_own_usb_interface_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_configuration_interfaces((self).__handle, ptr);
  *ret = (wadu436_usb_device_list_own_usb_interface_t) { (wadu436_usb_device_own_usb_interface_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wadu436_usb_device_method_usb_interface_descriptor(wadu436_usb_device_borrow_usb_interface_t self, wadu436_usb_device_interface_descriptor_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[20];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_interface_descriptor((self).__handle, ptr);
  bindings_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 8)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (bindings_string_t) { (uint8_t*)(*((int32_t*) (ptr + 12))), (size_t)(*((int32_t*) (ptr + 16))) };
      break;
    }
  }
  *ret = (wadu436_usb_descriptors_interface_descriptor_t) {
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 0)))),
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 1)))),
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 2)))),
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 3)))),
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 4)))),
    option,
  };
}

void wadu436_usb_device_method_usb_interface_endpoints(wadu436_usb_device_borrow_usb_interface_t self, wadu436_usb_device_list_own_usb_endpoint_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_interface_endpoints((self).__handle, ptr);
  *ret = (wadu436_usb_device_list_own_usb_endpoint_t) { (wadu436_usb_device_own_usb_endpoint_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wadu436_usb_device_method_usb_endpoint_descriptor(wadu436_usb_device_borrow_usb_endpoint_t self, wadu436_usb_device_endpoint_descriptor_t *ret) {
  __attribute__((__aligned__(2)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wadu436_usb_device_method_usb_endpoint_descriptor((self).__handle, ptr);
  *ret = (wadu436_usb_descriptors_endpoint_descriptor_t) {
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 0)))),
    (int32_t) (*((uint8_t*) (ptr + 1))),
    (int32_t) (*((uint8_t*) (ptr + 2))),
    (uint16_t) ((int32_t) (*((uint16_t*) (ptr + 4)))),
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 6)))),
  };
}

extern void __component_type_object_force_link_bindings(void);
void __component_type_object_force_link_bindings_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_bindings();
}
