// Some additional convenience trait implementations for types from the WIT interfaces
use crate::bindings::wadu436::usb::types::Filter;

// We implement this here instead because the bindings.rs file is autogenerated
#[allow(clippy::derivable_impls)]
impl Default for Filter {
    fn default() -> Self {
        Self {
            vendor_id: Default::default(),
            product_id: Default::default(),
            class_code: Default::default(),
            subclass_code: Default::default(),
            protocol_code: Default::default(),
            serial_number: Default::default(),
        }
    }
}
