package component:wasm-usb-app;

interface raw-frame-stream {
    record raw-frame {
        data:   list<u8>,
        width:  u32,
        height: u32,
    }

    resource frame-source {
        constructor(index: u32);
        next-frame: func() -> result<raw-frame, string>;
    }
}
