package component:usb;

world host {
    import transfers;
    import errors;
    import device;
    import descriptors;
    import configuration;
    import usb-hotplug;
    import component:wasm-usb-app/raw-frame-stream;
}

world guest {
    import transfers;
    import errors;
    import device;
    import descriptors;
    import configuration;
    import usb-hotplug;
}

world cguest {
    import transfers;
    import errors;
    import device;
    import descriptors;
    import configuration;
    import usb-hotplug;

    export wasi:cli/run@0.2.5;
}

world webcam-provider-host {
    import transfers;
    import errors;
    import device;
    import descriptors;
    import configuration;
    import usb-hotplug;
    
    // Exporting frame-transport so the host can link components implementing this world
    export component:frame-transport/raw-frame-stream@0.1.0;
}