package component:usb@0.2.1;

interface usb-hotplug {
    use errors.{libusb-error};
    use device.{usb-device};

    flags event { arrived, left }

    record info {
        bus: u8,
        address: u8,
        vendor: u16,
        product: u16,
    }

    enable-hotplug: func() -> result<_, libusb-error>;
    poll-events: func() -> list<tuple<event, info, usb-device>>;
}
