package component:usb@0.2.1;

world host {
    import transfers;
    import errors;
    import device;
    import descriptors;
    import configuration;
    import usb-hotplug;
    import cv;

    export transfers;
    export errors;
    export device;
    export descriptors;
    export configuration;
    export usb-hotplug;
    export cv;
}

world guest {
    import transfers;
    import errors;
    import device;
    import descriptors;
    import configuration;
    import usb-hotplug;
    import cv;
}

world cguest {
    import transfers;
    import errors;
    import device;
    import descriptors;
    import configuration;
    import usb-hotplug;
    import cv;

    export wasi:cli/run@0.2.5;
}